---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fs
  name: gop-fs-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
      protocol: TCP
  selector:
    app: fs
