---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      imagePullPolicy: IfNotPresent
      command:
        [ "jekyll", "new", "/site" ]
      volumeMounts:
        - mountPath: /site
          name: site
  containers:
    - name: jekyll
      image: kodekloud/jekyll-serve
      volumeMounts:
        - mountPath: /site
          name: site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
