---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  type: NodePort
  ports:
    - name: client
      port: 8080
      targetPort: 4000
      nodePort: 30097
      protocol: TCP
  selector:
    run: jekyll
status:
  loadBalancer: {}

