---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: db-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
        - name: db-app
          image: postgres:9.4
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          ports:
            - containerPort: 80
      volumes:
        - name: db-data
          emptyDir: {}


