---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: db-app
  namespace: vote
spec:
  ports:
  - port: 5432
    name: db-something
    targetPort: 5432
  selector:
     app: db-app
