---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app
  namespace: vote
spec:
  ports:
  - port: 6379
    name: redis-something
    targetPort: 6379
  selector:
     app: redis-app
