---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
  namespace: vote
spec:
  type: NodePort
  ports:
    - name: client
      port: 5001
      targetPort: 80
      nodePort: 31001
      protocol: TCP
  selector:
    app: result-app