---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: voting-app
  namespace: vote
spec:
  ports:
    - name: voter
      port: 5000
      targetPort: 80
      nodePort: 31000
      protocol: TCP
  type: NodePort
  selector:
    app: voting-app