---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
    app: worker-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-pod
          image: kodekloud/examplevotingapp_worker
          ports:
            - containerPort: 80
